version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  
  spot-finder:
    image: spot-finder
    build: ./spot-finder
    depends_on: ["nats"]
    networks: ["nats"]

networks:
  nats:
    name: nats
