[package]
name = "sunangel-home-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.27.1"
futures-util = "0.3.26"
serde = "1.0.152"
serde_json = "1.0.93"
tokio = "1.25.0"
uuid = { version = "1.3.0", features = ["v4"] }
